# -*- coding: utf-8 -*-
"""object detection and semantic segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-XPdT3q0izm5J9d5A3Gx6x_KB-YflIcp
"""

!pip install ultralytics

from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt

det_model = YOLO('yolov8x.pt')


seg_model = YOLO('yolov8x-seg.pt')

from google.colab import files
import cv2
import matplotlib.pyplot as plt
from ultralytics import YOLO


uploaded = files.upload()


img_path = list(uploaded.keys())[0]


img_bgr = cv2.imread(img_path)


img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)


det_model = YOLO("yolov8n.pt")


det_results = det_model.predict(img_rgb)

result_img = det_results[0].plot()
plt.imshow(result_img)
plt.axis('off')
plt.show()

seg_results = seg_model.predict(img_rgb)


seg_results[0].plot()
plt.imshow(seg_results[0].plot())
plt.axis('off')
plt.show()























